name: GitHub Actions AWS
run-name: ${{ github.actor }} is testing out GitHub Actions with AWS container
on: [push]
jobs:
  AWS-Actions:
    runs-on: ubuntu-latest
    container: amazon/aws-cli
    permissions:
      id-token: write # This is required for requesting the JWT
    steps:
      - name: configure aws credentials
        env:
          my_role: ${{ secrets.MY_ROLE }}
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: $my_role
          role-session-name: github-session
      - name: list buckets
        run: aws s3 ls
