name: GitHub Actions AWS
run-name: ${{ github.actor }} is testing out GitHub Actions with AWS container
on: [push]
jobs:
  aws:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # This is required for requesting the JWT
    steps:
      - name: configure aws credentials
        id: creds
        env:
          my_role: ${{ secrets.MY_ROLE }}
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: "arn:aws:iam::316382246604:role/cicd-github"
          aws-region: "eu-west-1"
          output-credentials: true
      - name: run aws commands
        run: |
           docker run \
           -e AWS_ACCESS_KEY_ID=${{ steps.creds.outputs.aws-access-key-id }} \
           -e AWS_SECRET_ACCESS_KEY=${{ steps.creds.outputs.aws-secret-access-key }} \
           -e AWS_SESSION_TOKEN=${{ steps.creds.outputs.aws-session-token }} \
           -e AWS_REGION="us-east-1" \
           amazon/aws-cli /bin/bash -c "aws s3 ls"
